# Generated by Django 4.0.3 on 2022-05-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_vetclinic', '0002_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupservice',
            name='photo',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
